<!DOCTYPE html>
<html lang="bn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IT Asset Inventory Report - Unnayan Prochesta</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 12px; color: #333; margin: 20px; }
        .header { text-align: center; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 22px; color: #4f46e5; }
        .header h2 { margin: 5px 0 0; font-size: 14px; color: #555; }
        .meta { display: flex; justify-content: space-between; margin-bottom: 15px; font-size: 11px; background: #f9fafb; padding: 10px; border-radius: 5px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f3f4f6; font-weight: bold; }
        .footer { margin-top: 50px; display: flex; justify-content: space-between; text-align: center; }
        .signature { border-top: 1px dashed #777; width: 180px; pt-2; font-size: 11px; }
        .no-print { margin-bottom: 20px; text-align: right; }
        .btn-print { background: #4f46e5; color: white; padding: 8px 16px; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; }
        @media print {
            .no-print { display: none; }
            body { margin: 0; }
        }
    </style>
</head>
<body>

    <div class="no-print">
        <button onclick="window.print()" class="btn-print">🖨️ Print / Save as PDF</button>
    </div>

    <div class="header">
        <h1>Unnayan Prochesta</h1>
        <h2>IT Infrastructure Asset Inventory Report</h2>
    </div>

    <div class="meta">
        <div>
            <strong>Report Scope:</strong> {{ $selectedBranch ? $selectedBranch->name : 'All Branches' }}<br>
            <strong>Total Assets Listed:</strong> {{ $assets->count() }}
        </div>
        <div style="text-align: right;">
            <strong>Generated Date:</strong> {{ now()->format('d M, Y h:i A') }}<br>
            <strong>Generated By:</strong> {{ Auth::user()->name }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>SL</th>
                <th>Asset Tag</th>
                <th>Asset Name</th>
                <th>Category</th>
                <th>Brand & Model</th>
                <th>Branch</th>
                <th>Status</th>
                <th>Purchase Cost</th>
            </tr>
        </thead>
        <tbody>
            @forelse($assets as $index => $asset)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td><strong>{{ $asset->asset_tag }}</strong></td>
                    <td>{{ $asset->name }}</td>
                    <td>{{ ucfirst($asset->category) }}</td>
                    <td>{{ $asset->brand }} {{ $asset->model ? '('.$asset->model.')' : '' }}</td>
                    <td>{{ $asset->branch->name }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $asset->status)) }}</td>
                    <td>{{ number_format($asset->purchase_cost, 2) }} BDT</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center; padding: 20px;">কোনো অ্যাসেট পাওয়া যায়নি।</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <div class="signature">Prepared By</div>
        <div class="signature">Verified By IT Officer</div>
        <div class="signature">Approved By Management</div>
    </div>

</body>
</html>